FROM python:3.12.0a1-slim-buster

WORKDIR /app

COPY code-reciever-backernd /app/code-reciever-backernd
# COPY . /app/

RUN mkdir /app/files

RUN chmod 777 /app/code-reciever-backernd

ENV CODE_EXTENSION=py
ENV SCRIPT="python /app/files/<FILENAME>/main.<CODE_EXTENSION>"

EXPOSE 3001

CMD [ "./code-reciever-backernd" ]
