# FROM nginx
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf


# Dockerfile

# Use the official NGINX image as the base image
FROM nginx:latest

# Copy the custom NGINX configuration file to the container
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 5000

# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]